#!/usr/bin/env python3

import sys
import sak.sak
import lib.error


def wrapped(argv):

    try:
        sak.sak.main(argv)

    except lib.error.MainException as e:
        print(e)

if __name__ == '__main__':
    wrapped(sys.argv[1:])
